config/routes.rb
Todo2::Application.routes.draw do
  resources :xptos

  devise_for :users

  root :to => 'pages#index'
  match '/pages/index' => 'pages#index', :as => :home
  get '/contatos' => 'pages#contatos', :as => :contatos
  get '/contato' => 'pages#contato', :as => :message
  post '/contato' => 'pages#salvar_contato', :as => :messages
  get '/editar_contato' => 'pages#editar_contato', :as => :edit_message
  get '/remover_contato' => 'pages#remover_contato', :as => :remover_contato
  put '/contato' => 'pages#salvar_edicao_do_contato'
  get '/mostrar_contato' => 'pages#mostrar_contato', :as => :mostrar_contato
  resource :apple

  resources :tasks

end

app/models/message.rb
class Message < ActiveRecord::Base
  attr_accessible :nome, :email, :mensagem
  validates :nome, :presence => true, :length => {:minimum => 2}
  validates :email, :presence => true
  validates :mensagem, :presence => true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :task_id

  belongs_to :task

  #has_and_belongs_to_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :description, :tags_text, :title



  #has_and_belongs_to_many :tags
  belongs_to :user
  has_many :tags

  after_save :create_tags

  def create_tags
    temp_tags_text = ""
    temp_tags_text = self.tags_text unless self.tags_text.blank?
    temp_tags_text.scan(/\B#([a-zA-Z ]+)/)
                  .map {|arrayed_tag| arrayed_tag.first.strip }
                  .each do |tag|
      self.tags << Tag.create(:name => tag)

    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :tasks
end

app/models/xpto.rb
class Xpto < ActiveRecord::Base
  attr_accessible :a
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
# encoding: utf-8

class PagesController < ApplicationController
  def index

  end

  def salvar_contato
    @message = Message.new(params[:message])
    @message.save
    flash[:message] = "Formulário enviado."
    render :contato
  end

  def contato
    @message = Message.new
  end

  def contatos
    @messages = Message.all
  end

  def mostrar_contato
    @message = Message.where(:id => params[:id]).first
  end

  def editar_contato
    @message = Message.where(:id => params[:id]).first
    render :contato
  end

  def salvar_edicao_do_contato
    @message = Message.find(params[:format])
    @message.update_attributes(params[:message])
    flash[:message] = "Contato editado."
    redirect_to contatos_path
  end

  def remover_contato
    message = Message.where(:id => params[:id]).first
    message.delete
    flash[:message] = "Contato removido."
    redirect_to contatos_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_filter :authenticate_user!

  respond_to :html, :js

  def index
    ap params[:tag]
    @task = Task.new
    @tasks = current_user.tasks
    @user_tags = Task.where(:user_id => current_user.id)
                    .map {|task| task.tags }
                    .flatten
                    .map {|tag| tag.name }
                    .uniq

    if params.include? :tag
      task_ids = @tasks.map(&:id)
      task_ids_of_tags = Tag.where("task_id IN (?) AND name = ?", task_ids, params[:tag] )
                .map(&:task_id)
      @tasks = Task.find(task_ids_of_tags)
    end
    
    respond_with @task
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    @task.user = current_user
    @task.save
    respond_with @task
  end
end

app/controllers/xptos_controller.rb
class XptosController < ApplicationController
  # GET /xptos
  # GET /xptos.json
  def index
    @xptos = Xpto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @xptos }
    end
  end

  # GET /xptos/1
  # GET /xptos/1.json
  def show
    @xpto = Xpto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @xpto }
    end
  end

  # GET /xptos/new
  # GET /xptos/new.json
  def new
    @xpto = Xpto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @xpto }
    end
  end

  # GET /xptos/1/edit
  def edit
    @xpto = Xpto.find(params[:id])
  end

  # POST /xptos
  # POST /xptos.json
  def create
    @xpto = Xpto.new(params[:xpto])

    respond_to do |format|
      if @xpto.save
        format.html { redirect_to @xpto, notice: 'Xpto was successfully created.' }
        format.json { render json: @xpto, status: :created, location: @xpto }
      else
        format.html { render action: "new" }
        format.json { render json: @xpto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /xptos/1
  # PUT /xptos/1.json
  def update
    @xpto = Xpto.find(params[:id])

    respond_to do |format|
      if @xpto.update_attributes(params[:xpto])
        format.html { redirect_to @xpto, notice: 'Xpto was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @xpto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /xptos/1
  # DELETE /xptos/1.json
  def destroy
    @xpto = Xpto.find(params[:id])
    @xpto.destroy

    respond_to do |format|
      format.html { redirect_to xptos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def imprime_ou_nao?(mensagem)
    return mensagem unless mensagem.nil?
    '<h1>nao imprime nada</h1>'.html_safe
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/xptos_helper.rb
module XptosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Todo2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/contato.html.erb
<h1>Contato</h1>
<%= form_for @message do |f| %>
  <%= f.error_messages %>

  <%= f.label :nome %>
  <%= f.text_field :nome %><br />
  <%= f.label :email %>
  <%= f.text_field :email %><br />
  <%= f.label :mensagem %>
  <%= f.text_area :mensagem %><br />

  <%= f.submit %>
  <!--
  <%= label_tag 'Nome' %>
  <%= text_field_tag 'nome' %><br />
  <%= label_tag 'Email' %>
  <%= text_field_tag 'email' %><br />
  <%= label_tag 'Mensagem' %>
  <%= text_area_tag 'mensagem' %><br />
  <%= submit_tag 'Enviar' %>
  -->
<% end %>

app/views/pages/contatos.html.erb
<h1>Contatos</h1>
<%= imprime_ou_nao? flash[:message] %>
<% @messages.each do |message| %>
  <b>Nome:</b><%= message.nome %><br />
  <b>E-mail:</b/><%= message.email %><br />
  <b>Mensagem:</b><%= message.mensagem %><br />
  <%= link_to 'Remover', remover_contato_path(:id => message.id) %>
  <%= link_to 'Editar', edit_message_path(:id => message.id) %>
  <%= link_to 'Mostrar', mostrar_contato_path(:id => message.id) %>
  <br /><br />
<% end %>

app/views/pages/index.html.erb
Esse é meu todo

app/views/pages/mostrar_contato.html.erb
  <b>Nome:</b><%= @message.nome %><br />
  <b>E-mail:</b/><%= @message.email %><br />
  <b>Mensagem:</b><%= @message.mensagem %><br />

app/views/tasks/_new.html.erb
<h1>Nova tarefa</h1>

<%= form_for @task, :remote => true do |f| %>
  <%= f.label 'Título' %><br />
  <%= f.text_field :title %><br />
  <%= f.label 'Descrição' %><br />
  <%= f.text_area :description, :style => 'width:171px;height:115px;' %><br />
  <%= f.label 'Tags' %><br />
  <%= f.text_field :tags_text %><br />
  <%= f.submit %>
<% end %>

app/views/tasks/_task_list.html.erb
<% @tasks.each do |task| %>
    <li><%= task.title %></li>
<% end %>

app/views/tasks/create.js.erb
$('#tasks').append('<li><%= @task.title %></li>');

app/views/tasks/index.html.erb
<h1>Tarefas</h1>

<p>Tags:
  <% @user_tags.each do |tag| %>
    <%= link_to '#' << tag, tasks_path({:tag => tag}), :remote => true  %>
  <% end %>
</p>

<ul id="tasks">
  <%= render :partial => 'task_list' %>
</ul>
<br />

<!-- 
<%= link_to 'Adicionar nova tarefa', new_task_path %>
-->

<%= render :partial => 'new' %>

app/views/tasks/index.js.erb
$('#tasks').html('<%= escape_javascript(render( :partial => 'task_list' )) %>');

app/views/tasks/new.html.erb
<h1>Nova tarefa</h1>

<%= form_for @task do |f| %>
  <%= f.label 'Título' %><br />
  <%= f.text_field :title %><br />
  <%= f.label 'Descrição' %><br />
  <%= f.text_area :description, :style => 'width:171px;height:115px;' %><br />
  <%= f.label 'Tags' %><br />
  <%= f.text_field :tags_text %><br />
  <%= f.submit %>
<% end %>

app/views/xptos/_form.html.erb
<%= form_for(@xpto) do |f| %>
  <% if @xpto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@xpto.errors.count, "error") %> prohibited this xpto from being saved:</h2>

      <ul>
      <% @xpto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :a %><br />
    <%= f.text_field :a %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/xptos/edit.html.erb
<h1>Editing xpto</h1>

<%= render 'form' %>

<%= link_to 'Show', @xpto %> |
<%= link_to 'Back', xptos_path %>

app/views/xptos/index.html.erb
<h1>Listing xptos</h1>

<table>
  <tr>
    <th>A</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @xptos.each do |xpto| %>
  <tr>
    <td><%= xpto.a %></td>
    <td><%= link_to 'Show', xpto %></td>
    <td><%= link_to 'Edit', edit_xpto_path(xpto) %></td>
    <td><%= link_to 'Destroy', xpto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Xpto', new_xpto_path %>

app/views/xptos/new.html.erb
<h1>New xpto</h1>

<%= render 'form' %>

<%= link_to 'Back', xptos_path %>

app/views/xptos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>A:</b>
  <%= @xpto.a %>
</p>


<%= link_to 'Edit', edit_xpto_path(@xpto) %> |
<%= link_to 'Back', xptos_path %>